export interface CityData {
  country: string;
  capital: string;
  timezone: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
}

export const POPULAR_CAPITALS: CityData[] = [
  { country: "France", capital: "Paris", timezone: "Europe/Paris" },
  { country: "United Kingdom", capital: "London", timezone: "Europe/London" },
  { country: "United States", capital: "Washington D.C.", timezone: "America/New_York" },
  { country: "Japan", capital: "Tokyo", timezone: "Asia/Tokyo" },
  { country: "Australia", capital: "Canberra", timezone: "Australia/Sydney" }, // Canberra utilise souvent le fuseau de Sydney/Melbourne
  { country: "Brazil", capital: "Brasília", timezone: "America/Sao_Paulo" },
  { country: "Canada", capital: "Ottawa", timezone: "America/Toronto" },
  { country: "Germany", capital: "Berlin", timezone: "Europe/Berlin" },
  { country: "India", capital: "New Delhi", timezone: "Asia/Kolkata" },
  { country: "China", capital: "Beijing", timezone: "Asia/Shanghai" },
];

export const ALL_CAPITALS: CityData[] = [
  ...POPULAR_CAPITALS,
  { country: "Afghanistan", capital: "Kabul", timezone: "Asia/Kabul" },
  { country: "Albania", capital: "Tirana", timezone: "Europe/Tirane" },
  { country: "Algeria", capital: "Algiers", timezone: "Africa/Algiers" },
  { country: "Argentina", capital: "Buenos Aires", timezone: "America/Argentina/Buenos_Aires" },
  { country: "Armenia", capital: "Yerevan", timezone: "Asia/Yerevan" },
  { country: "Austria", capital: "Vienna", timezone: "Europe/Vienna" },
  { country: "Azerbaijan", capital: "Baku", timezone: "Asia/Baku" },
  { country: "Bahamas", capital: "Nassau", timezone: "America/Nassau" },
  { country: "Bahrain", capital: "Manama", timezone: "Asia/Bahrain" },
  { country: "Bangladesh", capital: "Dhaka", timezone: "Asia/Dhaka" },
  { country: "Barbados", capital: "Bridgetown", timezone: "America/Barbados" },
  { country: "Belgium", capital: "Brussels", timezone: "Europe/Brussels" },
  { country: "Belize", capital: "Belmopan", timezone: "America/Belize" },
  { country: "Bolivia", capital: "Sucre", timezone: "America/La_Paz" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo", timezone: "Europe/Sarajevo" },
  { country: "Botswana", capital: "Gaborone", timezone: "Africa/Gaborone" },
  { country: "Bulgaria", capital: "Sofia", timezone: "Europe/Sofia" },
  { country: "Cambodia", capital: "Phnom Penh", timezone: "Asia/Phnom_Penh" },
  { country: "Cameroon", capital: "Yaoundé", timezone: "Africa/Douala" },
  { country: "Chile", capital: "Santiago", timezone: "America/Santiago" },
  { country: "Colombia", capital: "Bogotá", timezone: "America/Bogota" },
  { country: "Costa Rica", capital: "San José", timezone: "America/Costa_Rica" },
  { country: "Croatia", capital: "Zagreb", timezone: "Europe/Zagreb" },
  { country: "Cuba", capital: "Havana", timezone: "America/Havana" },
  { country: "Cyprus", capital: "Nicosia", timezone: "Asia/Nicosia" },
  { country: "Czech Republic", capital: "Prague", timezone: "Europe/Prague" },
  { country: "Denmark", capital: "Copenhagen", timezone: "Europe/Copenhagen" },
  { country: "Dominican Republic", capital: "Santo Domingo", timezone: "America/Santo_Domingo" },
  { country: "Egypt", capital: "Cairo", timezone: "Africa/Cairo" },
  { country: "Estonia", capital: "Tallinn", timezone: "Europe/Tallinn" },
  { country: "Ethiopia", capital: "Addis Ababa", timezone: "Africa/Addis_Ababa" },
  { country: "Fiji", capital: "Suva", timezone: "Pacific/Fiji" },
  { country: "Finland", capital: "Helsinki", timezone: "Europe/Helsinki" },
  { country: "Ghana", capital: "Accra", timezone: "Africa/Accra" },
  { country: "Greece", capital: "Athens", timezone: "Europe/Athens" },
  { country: "Guatemala", capital: "Guatemala City", timezone: "America/Guatemala" },
  { country: "Haiti", capital: "Port-au-Prince", timezone: "America/Port-au-Prince" },
  { country: "Honduras", capital: "Tegucigalpa", timezone: "America/Tegucigalpa" },
  { country: "Hungary", capital: "Budapest", timezone: "Europe/Budapest" },
  { country: "Iceland", capital: "Reykjavík", timezone: "Atlantic/Reykjavik" },
  { country: "Indonesia", capital: "Jakarta", timezone: "Asia/Jakarta" },
  { country: "Iran", capital: "Tehran", timezone: "Asia/Tehran" },
  { country: "Iraq", capital: "Baghdad", timezone: "Asia/Baghdad" },
  { country: "Ireland", capital: "Dublin", timezone: "Europe/Dublin" },
  { country: "Israel", capital: "Jerusalem", timezone: "Asia/Jerusalem" },
  { country: "Italy", capital: "Rome", timezone: "Europe/Rome" },
  { country: "Jamaica", capital: "Kingston", timezone: "America/Jamaica" },
  { country: "Jordan", capital: "Amman", timezone: "Asia/Amman" },
  { country: "Kenya", capital: "Nairobi", timezone: "Africa/Nairobi" },
  { country: "Kuwait", capital: "Kuwait City", timezone: "Asia/Kuwait" },
  { country: "Latvia", capital: "Riga", timezone: "Europe/Riga" },
  { country: "Lebanon", capital: "Beirut", timezone: "Asia/Beirut" },
  { country: "Lithuania", capital: "Vilnius", timezone: "Europe/Vilnius" },
  { country: "Luxembourg", capital: "Luxembourg", timezone: "Europe/Luxembourg" },
  { country: "Malaysia", capital: "Kuala Lumpur", timezone: "Asia/Kuala_Lumpur" },
  { country: "Maldives", capital: "Malé", timezone: "Indian/Maldives" },
  { country: "Mexico", capital: "Mexico City", timezone: "America/Mexico_City" },
  { country: "Monaco", capital: "Monaco", timezone: "Europe/Monaco" },
  { country: "Mongolia", capital: "Ulaanbaatar", timezone: "Asia/Ulaanbaatar" },
  { country: "Morocco", capital: "Rabat", timezone: "Africa/Casablanca" },
  { country: "Nepal", capital: "Kathmandu", timezone: "Asia/Kathmandu" },
  { country: "Netherlands", capital: "Amsterdam", timezone: "Europe/Amsterdam" },
  { country: "New Zealand", capital: "Wellington", timezone: "Pacific/Auckland" },
  { country: "Nigeria", capital: "Abuja", timezone: "Africa/Lagos" },
  { country: "North Korea", capital: "Pyongyang", timezone: "Asia/Pyongyang" },
  { country: "Norway", capital: "Oslo", timezone: "Europe/Oslo" },
  { country: "Pakistan", capital: "Islamabad", timezone: "Asia/Karachi" },
  { country: "Panama", capital: "Panama City", timezone: "America/Panama" },
  { country: "Peru", capital: "Lima", timezone: "America/Lima" },
  { country: "Philippines", capital: "Manila", timezone: "Asia/Manila" },
  { country: "Poland", capital: "Warsaw", timezone: "Europe/Warsaw" },
  { country: "Portugal", capital: "Lisbon", timezone: "Europe/Lisbon" },
  { country: "Qatar", capital: "Doha", timezone: "Asia/Qatar" },
  { country: "Romania", capital: "Bucharest", timezone: "Europe/Bucharest" },
  { country: "Russia", capital: "Moscow", timezone: "Europe/Moscow" },
  { country: "Saudi Arabia", capital: "Riyadh", timezone: "Asia/Riyadh" },
  { country: "Senegal", capital: "Dakar", timezone: "Africa/Dakar" },
  { country: "Serbia", capital: "Belgrade", timezone: "Europe/Belgrade" },
  { country: "Singapore", capital: "Singapore", timezone: "Asia/Singapore" },
  { country: "Slovakia", capital: "Bratislava", timezone: "Europe/Bratislava" },
  { country: "Slovenia", capital: "Ljubljana", timezone: "Europe/Ljubljana" },
  { country: "South Africa", capital: "Pretoria", timezone: "Africa/Johannesburg" },
  { country: "South Korea", capital: "Seoul", timezone: "Asia/Seoul" },
  { country: "Spain", capital: "Madrid", timezone: "Europe/Madrid" },
  { country: "Sri Lanka", capital: "Colombo", timezone: "Asia/Colombo" },
  { country: "Sweden", capital: "Stockholm", timezone: "Europe/Stockholm" },
  { country: "Switzerland", capital: "Bern", timezone: "Europe/Zurich" },
  { country: "Taiwan", capital: "Taipei", timezone: "Asia/Taipei" },
  { country: "Thailand", capital: "Bangkok", timezone: "Asia/Bangkok" },
  { country: "Tunisia", capital: "Tunis", timezone: "Africa/Tunis" },
  { country: "Turkey", capital: "Ankara", timezone: "Europe/Istanbul" },
  { country: "Ukraine", capital: "Kyiv", timezone: "Europe/Kiev" },
  { country: "United Arab Emirates", capital: "Abu Dhabi", timezone: "Asia/Dubai" },
  { country: "Uruguay", capital: "Montevideo", timezone: "America/Montevideo" },
  { country: "Venezuela", capital: "Caracas", timezone: "America/Caracas" },
  { country: "Vietnam", capital: "Hanoi", timezone: "Asia/Ho_Chi_Minh" },
  { country: "Zimbabwe", capital: "Harare", timezone: "Africa/Harare" }
].sort((a, b) => a.country.localeCompare(b.country));
